services:
  classicpress:
    image: classicpress/classicpress:php7.4-apache
    container_name: classicpress
    ports:
      - "8080:80"
    environment:
      CLASSICPRESS_DB_HOST: db:3306
      CLASSICPRESS_DB_USER: classicpress
      CLASSICPRESS_DB_PASSWORD: classicpress
      CLASSICPRESS_DB_NAME: classicpress
    volumes:
      - classicpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: classicpress_db
    restart: always
    environment:
      MYSQL_DATABASE: classicpress
      MYSQL_USER: classicpress
      MYSQL_PASSWORD: classicpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  classicpress_data:
  db_data:
