name: Build and Push Multi-Architecture Docker Images

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile:
          - ./php8.3/Dockerfile
          - ./php8.4/Dockerfile
        platform: 
          - linux/amd64
          - linux/arm64

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract Dockerfile version for tagging
      - name: Extract version from Dockerfile path
        id: extract_version
        run: echo "version=${{ matrix.dockerfile }}" | sed -E 's#.*/php(.*)/Dockerfile#php\1#' >> $GITHUB_ENV

      # Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/classicpress:${{ env.version }}
